# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 5.2.0-17368
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import corellium_api
from corellium_api.models.rate_info import RateInfo  # noqa: E501
from corellium_api.rest import ApiException

class TestRateInfo(unittest.TestCase):
    """RateInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RateInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = corellium_api.models.rate_info.RateInfo()  # noqa: E501
        if include_optional :
            return RateInfo(
                on_rate_microcents = 56, 
                off_rate_microcents = 56
            )
        else :
            return RateInfo(
        )

    def testRateInfo(self):
        """Test RateInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
