# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import corellium_api
from corellium_api.models.touch_curve_input import TouchCurveInput  # noqa: E501
from corellium_api.rest import ApiException

class TestTouchCurveInput(unittest.TestCase):
    """TouchCurveInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TouchCurveInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = corellium_api.models.touch_curve_input.TouchCurveInput()  # noqa: E501
        if include_optional :
            return TouchCurveInput(
                start = None, 
                end = None, 
                bezier_points = [
                    corellium_api.models.finger_positions.FingerPositions()
                    ], 
                start_buttons = [
                    null
                    ], 
                end_buttons = [
                    null
                    ], 
                normalized = True, 
                wait = 56, 
                duration = 56
            )
        else :
            return TouchCurveInput(
                start = None,
                end = None,
                start_buttons = [
                    null
                    ],
                duration = 56,
        )

    def testTouchCurveInput(self):
        """Test TouchCurveInput"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
