# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import corellium_api
from corellium_api.models.get_interconnects_response import GetInterconnectsResponse  # noqa: E501
from corellium_api.rest import ApiException

class TestGetInterconnectsResponse(unittest.TestCase):
    """GetInterconnectsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetInterconnectsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = corellium_api.models.get_interconnects_response.GetInterconnectsResponse()  # noqa: E501
        if include_optional :
            return GetInterconnectsResponse(
                results = [
                    corellium_api.models.interconnect_response.InterconnectResponse(
                        id = '', 
                        name = '', 
                        protocol = '', 
                        type = 'hub', 
                        project = '', 
                        status = '', 
                        interfaces = [
                            corellium_api.models.instance_interface.InstanceInterface(
                                device_id = '', 
                                interface_id = '', )
                            ], 
                        created_at = '', 
                        updated_at = '', )
                    ], 
                count = 1.337, 
                total = 1.337, 
                limit = 1.337, 
                offset = 1.337
            )
        else :
            return GetInterconnectsResponse(
        )

    def testGetInterconnectsResponse(self):
        """Test GetInterconnectsResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
