# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import corellium_api
from corellium_api.models.assessment import Assessment  # noqa: E501
from corellium_api.rest import ApiException

class TestAssessment(unittest.TestCase):
    """Assessment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssessment(self):
        """Test Assessment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
