# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import corellium_api
from corellium_api.models.team import Team  # noqa: E501
from corellium_api.rest import ApiException

class TestTeam(unittest.TestCase):
    """Team unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Team
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = corellium_api.models.team.Team()  # noqa: E501
        if include_optional :
            return Team(
                id = '', 
                label = '', 
                users = [
                    corellium_api.models.user.User(
                        id = '', 
                        label = '', 
                        name = '', 
                        email = '', 
                        administrator = True, 
                        can_edit_user_attributes = True, 
                        cluster_administrator = True, )
                    ]
            )
        else :
            return Team(
                id = '',
                label = '',
        )

    def testTeam(self):
        """Test Team"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
