# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import corellium_api
from corellium_api.models.user_create import UserCreate  # noqa: E501
from corellium_api.rest import ApiException

class TestUserCreate(unittest.TestCase):
    """UserCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = corellium_api.models.user_create.UserCreate()  # noqa: E501
        if include_optional :
            return UserCreate(
                name = '', 
                label = '', 
                password = '', 
                email = '', 
                administrator = True, 
                cluster_administrator = True
            )
        else :
            return UserCreate(
        )

    def testUserCreate(self):
        """Test UserCreate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
