# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class AssessmentHistoryLineItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'date': 'float',
        'complete': 'float',
        'incomplete': 'float'
    }

    attribute_map = {
        'date': 'date',
        'complete': 'complete',
        'incomplete': 'incomplete'
    }

    def __init__(self, date=None, complete=None, incomplete=None, local_vars_configuration=None):  # noqa: E501
        """AssessmentHistoryLineItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._date = None
        self._complete = None
        self._incomplete = None
        self.discriminator = None

        self.date = date
        self.complete = complete
        self.incomplete = incomplete

    @property
    def date(self):
        """Gets the date of this AssessmentHistoryLineItem.  # noqa: E501

        UNIX Date representing the month  # noqa: E501

        :return: The date of this AssessmentHistoryLineItem.  # noqa: E501
        :rtype: float
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this AssessmentHistoryLineItem.

        UNIX Date representing the month  # noqa: E501

        :param date: The date of this AssessmentHistoryLineItem.  # noqa: E501
        :type date: float
        """
        if self.local_vars_configuration.client_side_validation and date is None:  # noqa: E501
            raise ValueError("Invalid value for `date`, must not be `None`")  # noqa: E501

        self._date = date

    @property
    def complete(self):
        """Gets the complete of this AssessmentHistoryLineItem.  # noqa: E501

        The number of successful assessments  # noqa: E501

        :return: The complete of this AssessmentHistoryLineItem.  # noqa: E501
        :rtype: float
        """
        return self._complete

    @complete.setter
    def complete(self, complete):
        """Sets the complete of this AssessmentHistoryLineItem.

        The number of successful assessments  # noqa: E501

        :param complete: The complete of this AssessmentHistoryLineItem.  # noqa: E501
        :type complete: float
        """
        if self.local_vars_configuration.client_side_validation and complete is None:  # noqa: E501
            raise ValueError("Invalid value for `complete`, must not be `None`")  # noqa: E501

        self._complete = complete

    @property
    def incomplete(self):
        """Gets the incomplete of this AssessmentHistoryLineItem.  # noqa: E501

        The number of failed assessments  # noqa: E501

        :return: The incomplete of this AssessmentHistoryLineItem.  # noqa: E501
        :rtype: float
        """
        return self._incomplete

    @incomplete.setter
    def incomplete(self, incomplete):
        """Sets the incomplete of this AssessmentHistoryLineItem.

        The number of failed assessments  # noqa: E501

        :param incomplete: The incomplete of this AssessmentHistoryLineItem.  # noqa: E501
        :type incomplete: float
        """
        if self.local_vars_configuration.client_side_validation and incomplete is None:  # noqa: E501
            raise ValueError("Invalid value for `incomplete`, must not be `None`")  # noqa: E501

        self._incomplete = incomplete

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssessmentHistoryLineItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AssessmentHistoryLineItem):
            return True

        return self.to_dict() != other.to_dict()
