# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.9.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class ClusterConfigurationPayload(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'snapshot_limit': 'float',
        'coordinator_config': 'CoordinatorConfig'
    }

    attribute_map = {
        'snapshot_limit': 'snapshotLimit',
        'coordinator_config': 'coordinatorConfig'
    }

    def __init__(self, snapshot_limit=None, coordinator_config=None, local_vars_configuration=None):  # noqa: E501
        """ClusterConfigurationPayload - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._snapshot_limit = None
        self._coordinator_config = None
        self.discriminator = None

        self.snapshot_limit = snapshot_limit
        if coordinator_config is not None:
            self.coordinator_config = coordinator_config

    @property
    def snapshot_limit(self):
        """Gets the snapshot_limit of this ClusterConfigurationPayload.  # noqa: E501

        Designates the maximum number of snapshots that can be taken in a cluster  # noqa: E501

        :return: The snapshot_limit of this ClusterConfigurationPayload.  # noqa: E501
        :rtype: float
        """
        return self._snapshot_limit

    @snapshot_limit.setter
    def snapshot_limit(self, snapshot_limit):
        """Sets the snapshot_limit of this ClusterConfigurationPayload.

        Designates the maximum number of snapshots that can be taken in a cluster  # noqa: E501

        :param snapshot_limit: The snapshot_limit of this ClusterConfigurationPayload.  # noqa: E501
        :type snapshot_limit: float
        """

        self._snapshot_limit = snapshot_limit

    @property
    def coordinator_config(self):
        """Gets the coordinator_config of this ClusterConfigurationPayload.  # noqa: E501


        :return: The coordinator_config of this ClusterConfigurationPayload.  # noqa: E501
        :rtype: CoordinatorConfig
        """
        return self._coordinator_config

    @coordinator_config.setter
    def coordinator_config(self, coordinator_config):
        """Sets the coordinator_config of this ClusterConfigurationPayload.


        :param coordinator_config: The coordinator_config of this ClusterConfigurationPayload.  # noqa: E501
        :type coordinator_config: CoordinatorConfig
        """

        self._coordinator_config = coordinator_config

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterConfigurationPayload):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ClusterConfigurationPayload):
            return True

        return self.to_dict() != other.to_dict()
