# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.9.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class CoordinatorConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'usb_media_access_enabled': 'bool'
    }

    attribute_map = {
        'usb_media_access_enabled': 'usbMediaAccessEnabled'
    }

    def __init__(self, usb_media_access_enabled=None, local_vars_configuration=None):  # noqa: E501
        """CoordinatorConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._usb_media_access_enabled = None
        self.discriminator = None

        self.usb_media_access_enabled = usb_media_access_enabled

    @property
    def usb_media_access_enabled(self):
        """Gets the usb_media_access_enabled of this CoordinatorConfig.  # noqa: E501

        Designates the maximum number of snapshots that can be taken in a cluster  # noqa: E501

        :return: The usb_media_access_enabled of this CoordinatorConfig.  # noqa: E501
        :rtype: bool
        """
        return self._usb_media_access_enabled

    @usb_media_access_enabled.setter
    def usb_media_access_enabled(self, usb_media_access_enabled):
        """Sets the usb_media_access_enabled of this CoordinatorConfig.

        Designates the maximum number of snapshots that can be taken in a cluster  # noqa: E501

        :param usb_media_access_enabled: The usb_media_access_enabled of this CoordinatorConfig.  # noqa: E501
        :type usb_media_access_enabled: bool
        """

        self._usb_media_access_enabled = usb_media_access_enabled

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CoordinatorConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CoordinatorConfig):
            return True

        return self.to_dict() != other.to_dict()
