# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class Device(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'model': 'str',
        'name': 'str',
        'platform': 'str',
        'hwmodel': 'str',
        'bdid': 'str',
        'cpid': 'str',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'type': 'type',
        'model': 'model',
        'name': 'name',
        'platform': 'platform',
        'hwmodel': 'hwmodel',
        'bdid': 'bdid',
        'cpid': 'cpid',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt'
    }

    def __init__(self, type=None, model=None, name=None, platform=None, hwmodel=None, bdid=None, cpid=None, created_at=None, updated_at=None, local_vars_configuration=None):  # noqa: E501
        """Device - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._model = None
        self._name = None
        self._platform = None
        self._hwmodel = None
        self._bdid = None
        self._cpid = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None

        self.type = type
        self.model = model
        self.name = name
        self.platform = platform
        self.hwmodel = hwmodel
        self.bdid = bdid
        self.cpid = cpid
        self.created_at = created_at
        self.updated_at = updated_at

    @property
    def type(self):
        """Gets the type of this Device.  # noqa: E501

          # noqa: E501

        :return: The type of this Device.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Device.

          # noqa: E501

        :param type: The type of this Device.  # noqa: E501
        :type type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def model(self):
        """Gets the model of this Device.  # noqa: E501

          # noqa: E501

        :return: The model of this Device.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this Device.

          # noqa: E501

        :param model: The model of this Device.  # noqa: E501
        :type model: str
        """
        if self.local_vars_configuration.client_side_validation and model is None:  # noqa: E501
            raise ValueError("Invalid value for `model`, must not be `None`")  # noqa: E501

        self._model = model

    @property
    def name(self):
        """Gets the name of this Device.  # noqa: E501

          # noqa: E501

        :return: The name of this Device.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Device.

          # noqa: E501

        :param name: The name of this Device.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def platform(self):
        """Gets the platform of this Device.  # noqa: E501

          # noqa: E501

        :return: The platform of this Device.  # noqa: E501
        :rtype: str
        """
        return self._platform

    @platform.setter
    def platform(self, platform):
        """Sets the platform of this Device.

          # noqa: E501

        :param platform: The platform of this Device.  # noqa: E501
        :type platform: str
        """

        self._platform = platform

    @property
    def hwmodel(self):
        """Gets the hwmodel of this Device.  # noqa: E501

          # noqa: E501

        :return: The hwmodel of this Device.  # noqa: E501
        :rtype: str
        """
        return self._hwmodel

    @hwmodel.setter
    def hwmodel(self, hwmodel):
        """Sets the hwmodel of this Device.

          # noqa: E501

        :param hwmodel: The hwmodel of this Device.  # noqa: E501
        :type hwmodel: str
        """

        self._hwmodel = hwmodel

    @property
    def bdid(self):
        """Gets the bdid of this Device.  # noqa: E501

          # noqa: E501

        :return: The bdid of this Device.  # noqa: E501
        :rtype: str
        """
        return self._bdid

    @bdid.setter
    def bdid(self, bdid):
        """Sets the bdid of this Device.

          # noqa: E501

        :param bdid: The bdid of this Device.  # noqa: E501
        :type bdid: str
        """

        self._bdid = bdid

    @property
    def cpid(self):
        """Gets the cpid of this Device.  # noqa: E501

          # noqa: E501

        :return: The cpid of this Device.  # noqa: E501
        :rtype: str
        """
        return self._cpid

    @cpid.setter
    def cpid(self, cpid):
        """Sets the cpid of this Device.

          # noqa: E501

        :param cpid: The cpid of this Device.  # noqa: E501
        :type cpid: str
        """

        self._cpid = cpid

    @property
    def created_at(self):
        """Gets the created_at of this Device.  # noqa: E501

          # noqa: E501

        :return: The created_at of this Device.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Device.

          # noqa: E501

        :param created_at: The created_at of this Device.  # noqa: E501
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this Device.  # noqa: E501

          # noqa: E501

        :return: The updated_at of this Device.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Device.

          # noqa: E501

        :param updated_at: The updated_at of this Device.  # noqa: E501
        :type updated_at: str
        """

        self._updated_at = updated_at

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Device):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Device):
            return True

        return self.to_dict() != other.to_dict()
