# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class ExtendedFirmwareAssetInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'firmwares': 'list[str]',
        'instances': 'list[str]'
    }

    attribute_map = {
        'firmwares': 'firmwares',
        'instances': 'instances'
    }

    def __init__(self, firmwares=None, instances=None, local_vars_configuration=None):  # noqa: E501
        """ExtendedFirmwareAssetInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._firmwares = None
        self._instances = None
        self.discriminator = None

        self.firmwares = firmwares
        self.instances = instances

    @property
    def firmwares(self):
        """Gets the firmwares of this ExtendedFirmwareAssetInfo.  # noqa: E501

        Firmware Records from FW Service  # noqa: E501

        :return: The firmwares of this ExtendedFirmwareAssetInfo.  # noqa: E501
        :rtype: list[str]
        """
        return self._firmwares

    @firmwares.setter
    def firmwares(self, firmwares):
        """Sets the firmwares of this ExtendedFirmwareAssetInfo.

        Firmware Records from FW Service  # noqa: E501

        :param firmwares: The firmwares of this ExtendedFirmwareAssetInfo.  # noqa: E501
        :type firmwares: list[str]
        """
        if self.local_vars_configuration.client_side_validation and firmwares is None:  # noqa: E501
            raise ValueError("Invalid value for `firmwares`, must not be `None`")  # noqa: E501

        self._firmwares = firmwares

    @property
    def instances(self):
        """Gets the instances of this ExtendedFirmwareAssetInfo.  # noqa: E501

        Instances using one of the firmwares, and thus the asset  # noqa: E501

        :return: The instances of this ExtendedFirmwareAssetInfo.  # noqa: E501
        :rtype: list[str]
        """
        return self._instances

    @instances.setter
    def instances(self, instances):
        """Sets the instances of this ExtendedFirmwareAssetInfo.

        Instances using one of the firmwares, and thus the asset  # noqa: E501

        :param instances: The instances of this ExtendedFirmwareAssetInfo.  # noqa: E501
        :type instances: list[str]
        """
        if self.local_vars_configuration.client_side_validation and instances is None:  # noqa: E501
            raise ValueError("Invalid value for `instances`, must not be `None`")  # noqa: E501

        self._instances = instances

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExtendedFirmwareAssetInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExtendedFirmwareAssetInfo):
            return True

        return self.to_dict() != other.to_dict()
