# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class GpiosState(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'led': 'GpioStateDefinition',
        'button': 'GpioStateDefinition',
        'switch': 'GpioStateDefinition'
    }

    attribute_map = {
        'led': 'led',
        'button': 'button',
        'switch': 'switch'
    }

    def __init__(self, led=None, button=None, switch=None, local_vars_configuration=None):  # noqa: E501
        """GpiosState - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._led = None
        self._button = None
        self._switch = None
        self.discriminator = None

        if led is not None:
            self.led = led
        if button is not None:
            self.button = button
        if switch is not None:
            self.switch = switch

    @property
    def led(self):
        """Gets the led of this GpiosState.  # noqa: E501


        :return: The led of this GpiosState.  # noqa: E501
        :rtype: GpioStateDefinition
        """
        return self._led

    @led.setter
    def led(self, led):
        """Sets the led of this GpiosState.


        :param led: The led of this GpiosState.  # noqa: E501
        :type led: GpioStateDefinition
        """

        self._led = led

    @property
    def button(self):
        """Gets the button of this GpiosState.  # noqa: E501


        :return: The button of this GpiosState.  # noqa: E501
        :rtype: GpioStateDefinition
        """
        return self._button

    @button.setter
    def button(self, button):
        """Sets the button of this GpiosState.


        :param button: The button of this GpiosState.  # noqa: E501
        :type button: GpioStateDefinition
        """

        self._button = button

    @property
    def switch(self):
        """Gets the switch of this GpiosState.  # noqa: E501


        :return: The switch of this GpiosState.  # noqa: E501
        :rtype: GpioStateDefinition
        """
        return self._switch

    @switch.setter
    def switch(self, switch):
        """Sets the switch of this GpiosState.


        :param switch: The switch of this GpiosState.  # noqa: E501
        :type switch: GpioStateDefinition
        """

        self._switch = switch

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GpiosState):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GpiosState):
            return True

        return self.to_dict() != other.to_dict()
