# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class InterconnectResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'protocol': 'str',
        'type': 'str',
        'project': 'str',
        'status': 'str',
        'interfaces': 'list[InstanceInterface]',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'protocol': 'protocol',
        'type': 'type',
        'project': 'project',
        'status': 'status',
        'interfaces': 'interfaces',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt'
    }

    def __init__(self, id=None, name=None, protocol=None, type=None, project=None, status=None, interfaces=None, created_at=None, updated_at=None, local_vars_configuration=None):  # noqa: E501
        """InterconnectResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._protocol = None
        self._type = None
        self._project = None
        self._status = None
        self._interfaces = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None

        self.id = id
        self.name = name
        self.protocol = protocol
        self.type = type
        self.project = project
        self.status = status
        self.interfaces = interfaces
        self.created_at = created_at
        self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this InterconnectResponse.  # noqa: E501

        The interconnect identifier  # noqa: E501

        :return: The id of this InterconnectResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InterconnectResponse.

        The interconnect identifier  # noqa: E501

        :param id: The id of this InterconnectResponse.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this InterconnectResponse.  # noqa: E501

        The name of the interconnect  # noqa: E501

        :return: The name of this InterconnectResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InterconnectResponse.

        The name of the interconnect  # noqa: E501

        :param name: The name of this InterconnectResponse.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def protocol(self):
        """Gets the protocol of this InterconnectResponse.  # noqa: E501

        The protocol used by the interconnect  # noqa: E501

        :return: The protocol of this InterconnectResponse.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this InterconnectResponse.

        The protocol used by the interconnect  # noqa: E501

        :param protocol: The protocol of this InterconnectResponse.  # noqa: E501
        :type protocol: str
        """

        self._protocol = protocol

    @property
    def type(self):
        """Gets the type of this InterconnectResponse.  # noqa: E501

        The type of interconnect  # noqa: E501

        :return: The type of this InterconnectResponse.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InterconnectResponse.

        The type of interconnect  # noqa: E501

        :param type: The type of this InterconnectResponse.  # noqa: E501
        :type type: str
        """
        allowed_values = [None,"hub", "switch"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def project(self):
        """Gets the project of this InterconnectResponse.  # noqa: E501

        The UUID of the project  # noqa: E501

        :return: The project of this InterconnectResponse.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this InterconnectResponse.

        The UUID of the project  # noqa: E501

        :param project: The project of this InterconnectResponse.  # noqa: E501
        :type project: str
        """

        self._project = project

    @property
    def status(self):
        """Gets the status of this InterconnectResponse.  # noqa: E501

        The current status of the interconnect  # noqa: E501

        :return: The status of this InterconnectResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InterconnectResponse.

        The current status of the interconnect  # noqa: E501

        :param status: The status of this InterconnectResponse.  # noqa: E501
        :type status: str
        """

        self._status = status

    @property
    def interfaces(self):
        """Gets the interfaces of this InterconnectResponse.  # noqa: E501

        Array of instance interfaces  # noqa: E501

        :return: The interfaces of this InterconnectResponse.  # noqa: E501
        :rtype: list[InstanceInterface]
        """
        return self._interfaces

    @interfaces.setter
    def interfaces(self, interfaces):
        """Sets the interfaces of this InterconnectResponse.

        Array of instance interfaces  # noqa: E501

        :param interfaces: The interfaces of this InterconnectResponse.  # noqa: E501
        :type interfaces: list[InstanceInterface]
        """

        self._interfaces = interfaces

    @property
    def created_at(self):
        """Gets the created_at of this InterconnectResponse.  # noqa: E501

        Creation timestamp  # noqa: E501

        :return: The created_at of this InterconnectResponse.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this InterconnectResponse.

        Creation timestamp  # noqa: E501

        :param created_at: The created_at of this InterconnectResponse.  # noqa: E501
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this InterconnectResponse.  # noqa: E501

        Last update timestamp  # noqa: E501

        :return: The updated_at of this InterconnectResponse.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this InterconnectResponse.

        Last update timestamp  # noqa: E501

        :param updated_at: The updated_at of this InterconnectResponse.  # noqa: E501
        :type updated_at: str
        """

        self._updated_at = updated_at

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InterconnectResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InterconnectResponse):
            return True

        return self.to_dict() != other.to_dict()
