# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.9.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class MediaStore(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'identifier': 'str',
        'device': 'str',
        'fs_type': 'str',
        'fs_uuid': 'str',
        'label': 'str',
        'serial': 'str',
        'vendor': 'str',
        'model': 'str',
        'mount_policy': 'str',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'identifier': 'identifier',
        'device': 'device',
        'fs_type': 'fsType',
        'fs_uuid': 'fsUUID',
        'label': 'label',
        'serial': 'serial',
        'vendor': 'vendor',
        'model': 'model',
        'mount_policy': 'mountPolicy',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt'
    }

    def __init__(self, identifier=None, device=None, fs_type=None, fs_uuid=None, label=None, serial=None, vendor=None, model=None, mount_policy=None, created_at=None, updated_at=None, local_vars_configuration=None):  # noqa: E501
        """MediaStore - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._identifier = None
        self._device = None
        self._fs_type = None
        self._fs_uuid = None
        self._label = None
        self._serial = None
        self._vendor = None
        self._model = None
        self._mount_policy = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None

        self.identifier = identifier
        self.device = device
        self.fs_type = fs_type
        self.fs_uuid = fs_uuid
        self.label = label
        self.serial = serial
        self.vendor = vendor
        self.model = model
        self.mount_policy = mount_policy
        self.created_at = created_at
        self.updated_at = updated_at

    @property
    def identifier(self):
        """Gets the identifier of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The identifier of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this MediaStore.

          # noqa: E501

        :param identifier: The identifier of this MediaStore.  # noqa: E501
        :type identifier: str
        """

        self._identifier = identifier

    @property
    def device(self):
        """Gets the device of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The device of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device):
        """Sets the device of this MediaStore.

          # noqa: E501

        :param device: The device of this MediaStore.  # noqa: E501
        :type device: str
        """

        self._device = device

    @property
    def fs_type(self):
        """Gets the fs_type of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The fs_type of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._fs_type

    @fs_type.setter
    def fs_type(self, fs_type):
        """Sets the fs_type of this MediaStore.

          # noqa: E501

        :param fs_type: The fs_type of this MediaStore.  # noqa: E501
        :type fs_type: str
        """

        self._fs_type = fs_type

    @property
    def fs_uuid(self):
        """Gets the fs_uuid of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The fs_uuid of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._fs_uuid

    @fs_uuid.setter
    def fs_uuid(self, fs_uuid):
        """Sets the fs_uuid of this MediaStore.

          # noqa: E501

        :param fs_uuid: The fs_uuid of this MediaStore.  # noqa: E501
        :type fs_uuid: str
        """

        self._fs_uuid = fs_uuid

    @property
    def label(self):
        """Gets the label of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The label of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this MediaStore.

          # noqa: E501

        :param label: The label of this MediaStore.  # noqa: E501
        :type label: str
        """

        self._label = label

    @property
    def serial(self):
        """Gets the serial of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The serial of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._serial

    @serial.setter
    def serial(self, serial):
        """Sets the serial of this MediaStore.

          # noqa: E501

        :param serial: The serial of this MediaStore.  # noqa: E501
        :type serial: str
        """

        self._serial = serial

    @property
    def vendor(self):
        """Gets the vendor of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The vendor of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor):
        """Sets the vendor of this MediaStore.

          # noqa: E501

        :param vendor: The vendor of this MediaStore.  # noqa: E501
        :type vendor: str
        """

        self._vendor = vendor

    @property
    def model(self):
        """Gets the model of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The model of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this MediaStore.

          # noqa: E501

        :param model: The model of this MediaStore.  # noqa: E501
        :type model: str
        """

        self._model = model

    @property
    def mount_policy(self):
        """Gets the mount_policy of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The mount_policy of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._mount_policy

    @mount_policy.setter
    def mount_policy(self, mount_policy):
        """Sets the mount_policy of this MediaStore.

          # noqa: E501

        :param mount_policy: The mount_policy of this MediaStore.  # noqa: E501
        :type mount_policy: str
        """

        self._mount_policy = mount_policy

    @property
    def created_at(self):
        """Gets the created_at of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The created_at of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this MediaStore.

          # noqa: E501

        :param created_at: The created_at of this MediaStore.  # noqa: E501
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this MediaStore.  # noqa: E501

          # noqa: E501

        :return: The updated_at of this MediaStore.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this MediaStore.

          # noqa: E501

        :param updated_at: The updated_at of this MediaStore.  # noqa: E501
        :type updated_at: str
        """

        self._updated_at = updated_at

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MediaStore):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MediaStore):
            return True

        return self.to_dict() != other.to_dict()
