# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.9.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class SnapshotList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'results': 'list[ClusterSnapshot]',
        'offset': 'float',
        'limit': 'float',
        'count': 'float'
    }

    attribute_map = {
        'results': 'results',
        'offset': 'offset',
        'limit': 'limit',
        'count': 'count'
    }

    def __init__(self, results=None, offset=None, limit=None, count=None, local_vars_configuration=None):  # noqa: E501
        """SnapshotList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._results = None
        self._offset = None
        self._limit = None
        self._count = None
        self.discriminator = None

        self.results = results
        self.offset = offset
        self.limit = limit
        self.count = count

    @property
    def results(self):
        """Gets the results of this SnapshotList.  # noqa: E501

        List of snapshots  # noqa: E501

        :return: The results of this SnapshotList.  # noqa: E501
        :rtype: list[ClusterSnapshot]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this SnapshotList.

        List of snapshots  # noqa: E501

        :param results: The results of this SnapshotList.  # noqa: E501
        :type results: list[ClusterSnapshot]
        """

        self._results = results

    @property
    def offset(self):
        """Gets the offset of this SnapshotList.  # noqa: E501

        Offset for pagination, defaults to 0  # noqa: E501

        :return: The offset of this SnapshotList.  # noqa: E501
        :rtype: float
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this SnapshotList.

        Offset for pagination, defaults to 0  # noqa: E501

        :param offset: The offset of this SnapshotList.  # noqa: E501
        :type offset: float
        """

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this SnapshotList.  # noqa: E501

        Number of items to return, defaults to 100, minimum of 1 and maximum of 1000  # noqa: E501

        :return: The limit of this SnapshotList.  # noqa: E501
        :rtype: float
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this SnapshotList.

        Number of items to return, defaults to 100, minimum of 1 and maximum of 1000  # noqa: E501

        :param limit: The limit of this SnapshotList.  # noqa: E501
        :type limit: float
        """

        self._limit = limit

    @property
    def count(self):
        """Gets the count of this SnapshotList.  # noqa: E501

        Number of items in current response  # noqa: E501

        :return: The count of this SnapshotList.  # noqa: E501
        :rtype: float
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this SnapshotList.

        Number of items in current response  # noqa: E501

        :param count: The count of this SnapshotList.  # noqa: E501
        :type count: float
        """

        self._count = count

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SnapshotList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SnapshotList):
            return True

        return self.to_dict() != other.to_dict()
