# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.9.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class SnapshotRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'limit': 'float',
        'offset': 'float',
        'springboard': 'bool',
        'live': 'bool',
        'fresh': 'bool',
        'device_name': 'str',
        'task': 'str',
        'to': 'str',
        '_from': 'str',
        'order_by': 'str',
        'search': 'str'
    }

    attribute_map = {
        'limit': 'limit',
        'offset': 'offset',
        'springboard': 'springboard',
        'live': 'live',
        'fresh': 'fresh',
        'device_name': 'deviceName',
        'task': 'task',
        'to': 'to',
        '_from': 'from',
        'order_by': 'orderBy',
        'search': 'search'
    }

    def __init__(self, limit=None, offset=None, springboard=None, live=None, fresh=None, device_name=None, task=None, to=None, _from=None, order_by=None, search=None, local_vars_configuration=None):  # noqa: E501
        """SnapshotRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._limit = None
        self._offset = None
        self._springboard = None
        self._live = None
        self._fresh = None
        self._device_name = None
        self._task = None
        self._to = None
        self.__from = None
        self._order_by = None
        self._search = None
        self.discriminator = None

        self.limit = limit
        self.offset = offset
        self.springboard = springboard
        self.live = live
        self.fresh = fresh
        self.device_name = device_name
        self.task = task
        self.to = to
        self._from = _from
        self.order_by = order_by
        self.search = search

    @property
    def limit(self):
        """Gets the limit of this SnapshotRequest.  # noqa: E501

        Number of entries to return, defaults to 100  # noqa: E501

        :return: The limit of this SnapshotRequest.  # noqa: E501
        :rtype: float
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this SnapshotRequest.

        Number of entries to return, defaults to 100  # noqa: E501

        :param limit: The limit of this SnapshotRequest.  # noqa: E501
        :type limit: float
        """

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this SnapshotRequest.  # noqa: E501

        Number of rows to skip, defaults to 0  # noqa: E501

        :return: The offset of this SnapshotRequest.  # noqa: E501
        :rtype: float
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this SnapshotRequest.

        Number of rows to skip, defaults to 0  # noqa: E501

        :param offset: The offset of this SnapshotRequest.  # noqa: E501
        :type offset: float
        """

        self._offset = offset

    @property
    def springboard(self):
        """Gets the springboard of this SnapshotRequest.  # noqa: E501

        Denotes whether snapshot was a springboard snapshot  # noqa: E501

        :return: The springboard of this SnapshotRequest.  # noqa: E501
        :rtype: bool
        """
        return self._springboard

    @springboard.setter
    def springboard(self, springboard):
        """Sets the springboard of this SnapshotRequest.

        Denotes whether snapshot was a springboard snapshot  # noqa: E501

        :param springboard: The springboard of this SnapshotRequest.  # noqa: E501
        :type springboard: bool
        """

        self._springboard = springboard

    @property
    def live(self):
        """Gets the live of this SnapshotRequest.  # noqa: E501

        Denotes whether snapshot was a live snapshot  # noqa: E501

        :return: The live of this SnapshotRequest.  # noqa: E501
        :rtype: bool
        """
        return self._live

    @live.setter
    def live(self, live):
        """Sets the live of this SnapshotRequest.

        Denotes whether snapshot was a live snapshot  # noqa: E501

        :param live: The live of this SnapshotRequest.  # noqa: E501
        :type live: bool
        """

        self._live = live

    @property
    def fresh(self):
        """Gets the fresh of this SnapshotRequest.  # noqa: E501

        Denotes whether snapshot was created immediately after the device was restored  # noqa: E501

        :return: The fresh of this SnapshotRequest.  # noqa: E501
        :rtype: bool
        """
        return self._fresh

    @fresh.setter
    def fresh(self, fresh):
        """Sets the fresh of this SnapshotRequest.

        Denotes whether snapshot was created immediately after the device was restored  # noqa: E501

        :param fresh: The fresh of this SnapshotRequest.  # noqa: E501
        :type fresh: bool
        """

        self._fresh = fresh

    @property
    def device_name(self):
        """Gets the device_name of this SnapshotRequest.  # noqa: E501

        Name of device  # noqa: E501

        :return: The device_name of this SnapshotRequest.  # noqa: E501
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name):
        """Sets the device_name of this SnapshotRequest.

        Name of device  # noqa: E501

        :param device_name: The device_name of this SnapshotRequest.  # noqa: E501
        :type device_name: str
        """

        self._device_name = device_name

    @property
    def task(self):
        """Gets the task of this SnapshotRequest.  # noqa: E501

        Task being executed on snapshot  # noqa: E501

        :return: The task of this SnapshotRequest.  # noqa: E501
        :rtype: str
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this SnapshotRequest.

        Task being executed on snapshot  # noqa: E501

        :param task: The task of this SnapshotRequest.  # noqa: E501
        :type task: str
        """

        self._task = task

    @property
    def to(self):
        """Gets the to of this SnapshotRequest.  # noqa: E501

        Date to filter to, keyed off of createdAt  # noqa: E501

        :return: The to of this SnapshotRequest.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this SnapshotRequest.

        Date to filter to, keyed off of createdAt  # noqa: E501

        :param to: The to of this SnapshotRequest.  # noqa: E501
        :type to: str
        """

        self._to = to

    @property
    def _from(self):
        """Gets the _from of this SnapshotRequest.  # noqa: E501

        Date to filter from, keyed off of createdAt  # noqa: E501

        :return: The _from of this SnapshotRequest.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this SnapshotRequest.

        Date to filter from, keyed off of createdAt  # noqa: E501

        :param _from: The _from of this SnapshotRequest.  # noqa: E501
        :type _from: str
        """

        self.__from = _from

    @property
    def order_by(self):
        """Gets the order_by of this SnapshotRequest.  # noqa: E501

        Sorting order ('-createdAt' or 'createdAt'), defaults to -createdAt  # noqa: E501

        :return: The order_by of this SnapshotRequest.  # noqa: E501
        :rtype: str
        """
        return self._order_by

    @order_by.setter
    def order_by(self, order_by):
        """Sets the order_by of this SnapshotRequest.

        Sorting order ('-createdAt' or 'createdAt'), defaults to -createdAt  # noqa: E501

        :param order_by: The order_by of this SnapshotRequest.  # noqa: E501
        :type order_by: str
        """

        self._order_by = order_by

    @property
    def search(self):
        """Gets the search of this SnapshotRequest.  # noqa: E501

        Last filter applied and searches on snapshot / associated instance name and snapshot / instance id  # noqa: E501

        :return: The search of this SnapshotRequest.  # noqa: E501
        :rtype: str
        """
        return self._search

    @search.setter
    def search(self, search):
        """Sets the search of this SnapshotRequest.

        Last filter applied and searches on snapshot / associated instance name and snapshot / instance id  # noqa: E501

        :param search: The search of this SnapshotRequest.  # noqa: E501
        :type search: str
        """

        self._search = search

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SnapshotRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SnapshotRequest):
            return True

        return self.to_dict() != other.to_dict()
