# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class TestAssessmentDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'invert': 'bool',
        'grep': 'str'
    }

    attribute_map = {
        'invert': 'invert',
        'grep': 'grep'
    }

    def __init__(self, invert=None, grep=None, local_vars_configuration=None):  # noqa: E501
        """TestAssessmentDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._invert = None
        self._grep = None
        self.discriminator = None

        if invert is not None:
            self.invert = invert
        if grep is not None:
            self.grep = grep

    @property
    def invert(self):
        """Gets the invert of this TestAssessmentDto.  # noqa: E501


        :return: The invert of this TestAssessmentDto.  # noqa: E501
        :rtype: bool
        """
        return self._invert

    @invert.setter
    def invert(self, invert):
        """Sets the invert of this TestAssessmentDto.


        :param invert: The invert of this TestAssessmentDto.  # noqa: E501
        :type invert: bool
        """

        self._invert = invert

    @property
    def grep(self):
        """Gets the grep of this TestAssessmentDto.  # noqa: E501


        :return: The grep of this TestAssessmentDto.  # noqa: E501
        :rtype: str
        """
        return self._grep

    @grep.setter
    def grep(self, grep):
        """Sets the grep of this TestAssessmentDto.


        :param grep: The grep of this TestAssessmentDto.  # noqa: E501
        :type grep: str
        """

        self._grep = grep

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestAssessmentDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TestAssessmentDto):
            return True

        return self.to_dict() != other.to_dict()
