# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class TextInput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'required': 'str',
        'key_duration': 'float'
    }

    attribute_map = {
        'required': 'required',
        'key_duration': 'keyDuration'
    }

    def __init__(self, required=None, key_duration=None, local_vars_configuration=None):  # noqa: E501
        """TextInput - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._required = None
        self._key_duration = None
        self.discriminator = None

        self.required = required
        self.key_duration = key_duration

    @property
    def required(self):
        """Gets the required of this TextInput.  # noqa: E501

        text to type  # noqa: E501

        :return: The required of this TextInput.  # noqa: E501
        :rtype: str
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this TextInput.

        text to type  # noqa: E501

        :param required: The required of this TextInput.  # noqa: E501
        :type required: str
        """
        if self.local_vars_configuration.client_side_validation and required is None:  # noqa: E501
            raise ValueError("Invalid value for `required`, must not be `None`")  # noqa: E501

        self._required = required

    @property
    def key_duration(self):
        """Gets the key_duration of this TextInput.  # noqa: E501

        How long to take to type each key.  150ms if not defined.  # noqa: E501

        :return: The key_duration of this TextInput.  # noqa: E501
        :rtype: float
        """
        return self._key_duration

    @key_duration.setter
    def key_duration(self, key_duration):
        """Sets the key_duration of this TextInput.

        How long to take to type each key.  150ms if not defined.  # noqa: E501

        :param key_duration: The key_duration of this TextInput.  # noqa: E501
        :type key_duration: float
        """

        self._key_duration = key_duration

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TextInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TextInput):
            return True

        return self.to_dict() != other.to_dict()
