# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class User(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'label': 'str',
        'name': 'str',
        'email': 'str',
        'administrator': 'bool',
        'can_edit_user_attributes': 'bool',
        'cluster_administrator': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'label': 'label',
        'name': 'name',
        'email': 'email',
        'administrator': 'administrator',
        'can_edit_user_attributes': 'canEditUserAttributes',
        'cluster_administrator': 'clusterAdministrator'
    }

    def __init__(self, id=None, label=None, name=None, email=None, administrator=None, can_edit_user_attributes=None, cluster_administrator=None, local_vars_configuration=None):  # noqa: E501
        """User - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._label = None
        self._name = None
        self._email = None
        self._administrator = None
        self._can_edit_user_attributes = None
        self._cluster_administrator = None
        self.discriminator = None

        self.id = id
        self.label = label
        self.name = name
        self.email = email
        self.administrator = administrator
        self.can_edit_user_attributes = can_edit_user_attributes
        self.cluster_administrator = cluster_administrator

    @property
    def id(self):
        """Gets the id of this User.  # noqa: E501

        User ID  # noqa: E501

        :return: The id of this User.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.

        User ID  # noqa: E501

        :param id: The id of this User.  # noqa: E501
        :type id: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def label(self):
        """Gets the label of this User.  # noqa: E501

        User Label  # noqa: E501

        :return: The label of this User.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this User.

        User Label  # noqa: E501

        :param label: The label of this User.  # noqa: E501
        :type label: str
        """
        if self.local_vars_configuration.client_side_validation and label is None:  # noqa: E501
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def name(self):
        """Gets the name of this User.  # noqa: E501

        User Name  # noqa: E501

        :return: The name of this User.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this User.

        User Name  # noqa: E501

        :param name: The name of this User.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def email(self):
        """Gets the email of this User.  # noqa: E501

        User Email  # noqa: E501

        :return: The email of this User.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this User.

        User Email  # noqa: E501

        :param email: The email of this User.  # noqa: E501
        :type email: str
        """
        if self.local_vars_configuration.client_side_validation and email is None:  # noqa: E501
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def administrator(self):
        """Gets the administrator of this User.  # noqa: E501

        the flag that specifies whether user is Administrator or not  # noqa: E501

        :return: The administrator of this User.  # noqa: E501
        :rtype: bool
        """
        return self._administrator

    @administrator.setter
    def administrator(self, administrator):
        """Sets the administrator of this User.

        the flag that specifies whether user is Administrator or not  # noqa: E501

        :param administrator: The administrator of this User.  # noqa: E501
        :type administrator: bool
        """

        self._administrator = administrator

    @property
    def can_edit_user_attributes(self):
        """Gets the can_edit_user_attributes of this User.  # noqa: E501

        Flag to determine if user attributes are editable.  # noqa: E501

        :return: The can_edit_user_attributes of this User.  # noqa: E501
        :rtype: bool
        """
        return self._can_edit_user_attributes

    @can_edit_user_attributes.setter
    def can_edit_user_attributes(self, can_edit_user_attributes):
        """Sets the can_edit_user_attributes of this User.

        Flag to determine if user attributes are editable.  # noqa: E501

        :param can_edit_user_attributes: The can_edit_user_attributes of this User.  # noqa: E501
        :type can_edit_user_attributes: bool
        """

        self._can_edit_user_attributes = can_edit_user_attributes

    @property
    def cluster_administrator(self):
        """Gets the cluster_administrator of this User.  # noqa: E501

        the flag that specifies whether user is cluster administrator or not  # noqa: E501

        :return: The cluster_administrator of this User.  # noqa: E501
        :rtype: bool
        """
        return self._cluster_administrator

    @cluster_administrator.setter
    def cluster_administrator(self, cluster_administrator):
        """Sets the cluster_administrator of this User.

        the flag that specifies whether user is cluster administrator or not  # noqa: E501

        :param cluster_administrator: The cluster_administrator of this User.  # noqa: E501
        :type cluster_administrator: bool
        """

        self._cluster_administrator = cluster_administrator

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, User):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, User):
            return True

        return self.to_dict() != other.to_dict()
