# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 7.6.0-29198
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class UserCreate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'label': 'str',
        'password': 'str',
        'email': 'str',
        'administrator': 'bool',
        'cluster_administrator': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'label': 'label',
        'password': 'password',
        'email': 'email',
        'administrator': 'administrator',
        'cluster_administrator': 'clusterAdministrator'
    }

    def __init__(self, name=None, label=None, password=None, email=None, administrator=None, cluster_administrator=None, local_vars_configuration=None):  # noqa: E501
        """UserCreate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._label = None
        self._password = None
        self._email = None
        self._administrator = None
        self._cluster_administrator = None
        self.discriminator = None

        self.name = name
        self.label = label
        self.password = password
        self.email = email
        self.administrator = administrator
        self.cluster_administrator = cluster_administrator

    @property
    def name(self):
        """Gets the name of this UserCreate.  # noqa: E501

        The user name.  # noqa: E501

        :return: The name of this UserCreate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserCreate.

        The user name.  # noqa: E501

        :param name: The name of this UserCreate.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def label(self):
        """Gets the label of this UserCreate.  # noqa: E501

        The user label (e.g., \"Domain Administrator\").  # noqa: E501

        :return: The label of this UserCreate.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this UserCreate.

        The user label (e.g., \"Domain Administrator\").  # noqa: E501

        :param label: The label of this UserCreate.  # noqa: E501
        :type label: str
        """

        self._label = label

    @property
    def password(self):
        """Gets the password of this UserCreate.  # noqa: E501

        The password (optional) if using SSO.  # noqa: E501

        :return: The password of this UserCreate.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UserCreate.

        The password (optional) if using SSO.  # noqa: E501

        :param password: The password of this UserCreate.  # noqa: E501
        :type password: str
        """

        self._password = password

    @property
    def email(self):
        """Gets the email of this UserCreate.  # noqa: E501

        The email (optional) if onsite.  # noqa: E501

        :return: The email of this UserCreate.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserCreate.

        The email (optional) if onsite.  # noqa: E501

        :param email: The email of this UserCreate.  # noqa: E501
        :type email: str
        """

        self._email = email

    @property
    def administrator(self):
        """Gets the administrator of this UserCreate.  # noqa: E501

        Whether the user is a domain administrator. Only users with the Domain Administrator role can set this.  # noqa: E501

        :return: The administrator of this UserCreate.  # noqa: E501
        :rtype: bool
        """
        return self._administrator

    @administrator.setter
    def administrator(self, administrator):
        """Sets the administrator of this UserCreate.

        Whether the user is a domain administrator. Only users with the Domain Administrator role can set this.  # noqa: E501

        :param administrator: The administrator of this UserCreate.  # noqa: E501
        :type administrator: bool
        """

        self._administrator = administrator

    @property
    def cluster_administrator(self):
        """Gets the cluster_administrator of this UserCreate.  # noqa: E501

        Whether the user is a cluster administrator. Only users with the Cluster Administrator role can set this.  # noqa: E501

        :return: The cluster_administrator of this UserCreate.  # noqa: E501
        :rtype: bool
        """
        return self._cluster_administrator

    @cluster_administrator.setter
    def cluster_administrator(self, cluster_administrator):
        """Sets the cluster_administrator of this UserCreate.

        Whether the user is a cluster administrator. Only users with the Cluster Administrator role can set this.  # noqa: E501

        :param cluster_administrator: The cluster_administrator of this UserCreate.  # noqa: E501
        :type cluster_administrator: bool
        """

        self._cluster_administrator = cluster_administrator

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserCreate):
            return True

        return self.to_dict() != other.to_dict()
