# coding: utf-8

"""
    Corellium API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.11.0-13738
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from corellium_api.configuration import Configuration


class VolumeOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'allocate': 'float',
        'partitions': 'list[object]',
        'compute_node': 'str'
    }

    attribute_map = {
        'allocate': 'allocate',
        'partitions': 'partitions',
        'compute_node': 'computeNode'
    }

    def __init__(self, allocate=None, partitions=None, compute_node=None, local_vars_configuration=None):  # noqa: E501
        """VolumeOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._allocate = None
        self._partitions = None
        self._compute_node = None
        self.discriminator = None

        self.allocate = allocate
        self.partitions = partitions
        self.compute_node = compute_node

    @property
    def allocate(self):
        """Gets the allocate of this VolumeOptions.  # noqa: E501

        GB  # noqa: E501

        :return: The allocate of this VolumeOptions.  # noqa: E501
        :rtype: float
        """
        return self._allocate

    @allocate.setter
    def allocate(self, allocate):
        """Sets the allocate of this VolumeOptions.

        GB  # noqa: E501

        :param allocate: The allocate of this VolumeOptions.  # noqa: E501
        :type allocate: float
        """

        self._allocate = allocate

    @property
    def partitions(self):
        """Gets the partitions of this VolumeOptions.  # noqa: E501


        :return: The partitions of this VolumeOptions.  # noqa: E501
        :rtype: list[object]
        """
        return self._partitions

    @partitions.setter
    def partitions(self, partitions):
        """Sets the partitions of this VolumeOptions.


        :param partitions: The partitions of this VolumeOptions.  # noqa: E501
        :type partitions: list[object]
        """

        self._partitions = partitions

    @property
    def compute_node(self):
        """Gets the compute_node of this VolumeOptions.  # noqa: E501


        :return: The compute_node of this VolumeOptions.  # noqa: E501
        :rtype: str
        """
        return self._compute_node

    @compute_node.setter
    def compute_node(self, compute_node):
        """Sets the compute_node of this VolumeOptions.


        :param compute_node: The compute_node of this VolumeOptions.  # noqa: E501
        :type compute_node: str
        """

        self._compute_node = compute_node

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumeOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VolumeOptions):
            return True

        return self.to_dict() != other.to_dict()
